# Site Configuration
baseURL = "https://drasi.io/"
title = "Drasi Docs"
theme = "docsy"

# Attribution
author = "Azure Incubations"
copyright = "Copyright © 2024, The Drasi Authors."

# Language Configuration
languageCode = "en"
DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokailight'

      
# Top Nav Bar
[[menu.main]]
    name = "GitHub"
    weight = 20
    url = "https://github.com/drasi-project"
    pre = "<i class='fab fa-github'></i>"
[[menu.main]]
    name = "Discord"
    weight = 30
    url = "https://aka.ms/drasidiscord"
    pre = "<i class='fab fa-discord'></i>"

[module]
  [module.hugoVersion]
    extended = true

# UI Customization
[params]
  prism_syntax_highlighting = true
  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "json"
    ]

[params.ui]
  sidebar_menu_compact = true
  sidebar_search_disable = true
  sidebar_menu_foldable = true
  sidebar_menu_truncate = 500
  ul_show = 1
  navbar_logo = true