# Site Configuration
baseURL = "https://drasi.io/"
title = "Drasi Docs"
theme = "docsy"

# Attribution
author = "Copyright © contributors to Drasi, established as Drasi a Series of LF Projects, LLC"
copyright ="""Copyright&nbsp;©&nbsp;Drasi&nbsp;a&nbsp;Series&nbsp;of&nbsp;LF&nbsp;Projects,&nbsp;LLC. For&nbsp;website&nbsp;terms&nbsp;of&nbsp;use,&nbsp;trademark&nbsp;policy&nbsp;and&nbsp;other&nbsp;project&nbsp;policies&nbsp;please&nbsp;see&nbsp;<a href="https://lfprojects.org/policies/">lfprojects.org/policies/</a>."""
# Language Configuration
languageCode = "en"
DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokailight'

      
# Top Nav Bar
[[menu.main]]
    name = "GitHub"
    weight = 10
    url = "https://github.com/drasi-project"
    pre = "<i class='fab fa-github'></i>"
[[menu.main]]
    name = "Discord"
    weight = 20
    url = "https://aka.ms/drasidiscord"
    pre = "<i class='fab fa-discord'></i>"

[[menu.main]]
    name = "YouTube"
    weight = 30
    url = "https://www.youtube.com/@DrasiProject"
    pre = "<i class='fab fa-youtube'></i>"

    [[menu.main]]
    name = "Bluesky"
    weight = 40
    url = "https://bsky.app/profile/drasi-project.bsky.social"
    pre = "<i class='fa-brands fa-bluesky'></i>"
    
[[menu.main]]
  name ="X"
  weight = 50
  url = "https://x.com/drasi_project"
  icon = "fa-brands fa-x-twitter"
  desc = "Follow us on X to get the latest news!"

[module]
  [module.hugoVersion]
    extended = true

[params.search.algolia]
appId = "Q8GYM4KCMH"
apiKey = "b7594fb9d03b1498e770a5a7a1065e95"
indexName = "drasi"

# UI Customization
[params]
  prism_syntax_highlighting = true
  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "json"
    ]
custom_js = ["js/sync-tabs.js"]
# Google Analytics
googleAnalytics =  "G-MZQ63ZL6GZ"

[params.ui]
  sidebar_menu_compact = true
  sidebar_search_disable = true
  sidebar_menu_foldable = true
  sidebar_menu_truncate = 500
  ul_show = 1
  navbar_logo = true
